[jobs]
    # if true, the default jobs are enabled. WARNING: setting this to false will erase all the stats for these jobs
    # Allowed values: true, false - Default: true
    enable_default_jobs = true

    # the amount of free jobs a player can have
    # Allowed range: 0 ~ 2147483647 - Default: 2
    amount_of_free_jobs = 2

    # the percentage of the job cost that is refunded when a player stops a job
    # Allowed range: 0 ~ 100 - Default: 50
    job_stop_refund_percentage = 50

    # if true, players can stop a job and get a refund
    # Allowed values: true, false - Default: false
    allow_job_stop_refund = false

    [jobs.coins]
        # the amount of coins a player gets when they level up a job
        # Allowed range: 0 ~ 2147483647 - Default: 1
        coins_per_level_up = 1

[debug]
    # if true, debug mode is enabled
    # Allowed values: true, false - Default: false
    is_debug = false

